# 1. The Database Connection (REQUIRED for Cloud)
# Notice the port is 6543, NOT 5432
DB_URL = "postgresql://postgres.project:admin@aws-0-ap-southeast-1.pooler.supabase.com:6543/postgres"

# 2. The Admin Password
ADMIN_PASSWORD = "admin"
